
// AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT
//

#ifdef __NODE_DECLARATIONS_ONLY__

namespace cdk {

class add_node;
class and_node;
class assignment_node;
class basic_node;
class binary_operation_node;
class data_node;
class div_node;
class double_node;
class eq_node;
class expression_node;
class ge_node;
class gt_node;
class integer_node;
class le_node;
template <typename StoredType> class literal_node;
class lt_node;
class lvalue_node;
class mod_node;
class mul_node;
class neg_node;
class ne_node;
class nil_node;
class not_node;
class or_node;
PaxHeaders.class add_node;
PaxHeaders.class and_node;
PaxHeaders.class assignment_node;
PaxHeaders.class basic_node;
PaxHeaders.class binary_operation_node;
PaxHeaders.class data_node;
PaxHeaders.class div_node;
PaxHeaders.class double_node;
PaxHeaders.class eq_node;
PaxHeaders.class expression_node;
PaxHeaders.class ge_node;
PaxHeaders.class gt_node;
PaxHeaders.class integer_node;
PaxHeaders.class le_node;
PaxHeaders.class literal_node;
PaxHeaders.class lt_node;
PaxHeaders.class lvalue_node;
PaxHeaders.class mod_node;
PaxHeaders.class mul_node;
PaxHeaders.class neg_node;
PaxHeaders.class ne_node;
PaxHeaders.class nil_node;
PaxHeaders.class not_node;
PaxHeaders.class or_node;
PaxHeaders.class rvalue_node;
PaxHeaders.class sequence_node;
PaxHeaders.class string_node;
PaxHeaders.class sub_node;
PaxHeaders.class typed_node;
PaxHeaders.class unary_operation_node;
PaxHeaders.class variable_node;
class rvalue_node;
class sequence_node;
class string_node;
class sub_node;
class typed_node;
class unary_operation_node;
class variable_node;


} // namespace cdk

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_cdk_NODE_ALLNODES_H__
#define __AUTOMATIC_cdk_NODE_ALLNODES_H__

#include <cdk/ast/add_node.h>
#include <cdk/ast/and_node.h>
#include <cdk/ast/assignment_node.h>
#include <cdk/ast/basic_node.h>
#include <cdk/ast/binary_operation_node.h>
#include <cdk/ast/data_node.h>
#include <cdk/ast/div_node.h>
#include <cdk/ast/double_node.h>
#include <cdk/ast/eq_node.h>
#include <cdk/ast/expression_node.h>
#include <cdk/ast/ge_node.h>
#include <cdk/ast/gt_node.h>
#include <cdk/ast/integer_node.h>
#include <cdk/ast/le_node.h>
#include <cdk/ast/literal_node.h>
#include <cdk/ast/lt_node.h>
#include <cdk/ast/lvalue_node.h>
#include <cdk/ast/mod_node.h>
#include <cdk/ast/mul_node.h>
#include <cdk/ast/neg_node.h>
#include <cdk/ast/ne_node.h>
#include <cdk/ast/nil_node.h>
#include <cdk/ast/not_node.h>
#include <cdk/ast/or_node.h>
PaxHeaders.4088/#include <cdk/ast/add_node.h>
PaxHeaders.4088/#include <cdk/ast/and_node.h>
PaxHeaders.4088/#include <cdk/ast/assignment_node.h>
PaxHeaders.4088/#include <cdk/ast/basic_node.h>
PaxHeaders.4088/#include <cdk/ast/binary_operation_node.h>
PaxHeaders.4088/#include <cdk/ast/data_node.h>
PaxHeaders.4088/#include <cdk/ast/div_node.h>
PaxHeaders.4088/#include <cdk/ast/double_node.h>
PaxHeaders.4088/#include <cdk/ast/eq_node.h>
PaxHeaders.4088/#include <cdk/ast/expression_node.h>
PaxHeaders.4088/#include <cdk/ast/ge_node.h>
PaxHeaders.4088/#include <cdk/ast/gt_node.h>
PaxHeaders.4088/#include <cdk/ast/integer_node.h>
PaxHeaders.4088/#include <cdk/ast/le_node.h>
PaxHeaders.4088/#include <cdk/ast/literal_node.h>
PaxHeaders.4088/#include <cdk/ast/lt_node.h>
PaxHeaders.4088/#include <cdk/ast/lvalue_node.h>
PaxHeaders.4088/#include <cdk/ast/mod_node.h>
PaxHeaders.4088/#include <cdk/ast/mul_node.h>
PaxHeaders.4088/#include <cdk/ast/neg_node.h>
PaxHeaders.4088/#include <cdk/ast/ne_node.h>
PaxHeaders.4088/#include <cdk/ast/nil_node.h>
PaxHeaders.4088/#include <cdk/ast/not_node.h>
PaxHeaders.4088/#include <cdk/ast/or_node.h>
PaxHeaders.4088/#include <cdk/ast/rvalue_node.h>
PaxHeaders.4088/#include <cdk/ast/sequence_node.h>
PaxHeaders.4088/#include <cdk/ast/string_node.h>
PaxHeaders.4088/#include <cdk/ast/sub_node.h>
PaxHeaders.4088/#include <cdk/ast/typed_node.h>
PaxHeaders.4088/#include <cdk/ast/unary_operation_node.h>
PaxHeaders.4088/#include <cdk/ast/variable_node.h>
#include <cdk/ast/rvalue_node.h>
#include <cdk/ast/sequence_node.h>
#include <cdk/ast/string_node.h>
#include <cdk/ast/sub_node.h>
#include <cdk/ast/typed_node.h>
#include <cdk/ast/unary_operation_node.h>
#include <cdk/ast/variable_node.h>


#endif /* !defined(__AUTOMATIC_cdk_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

