
// AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT

#ifdef __IN_VISITOR_HEADER__
#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__
  virtual void do_add_node(cdk::add_node *const node, int lvl) = 0;
  virtual void do_and_node(cdk::and_node *const node, int lvl) = 0;
  virtual void do_assignment_node(cdk::assignment_node *const node, int lvl) = 0;
  virtual void do_data_node(cdk::data_node *const node, int lvl) = 0;
  virtual void do_div_node(cdk::div_node *const node, int lvl) = 0;
  virtual void do_double_node(cdk::double_node *const node, int lvl) = 0;
  virtual void do_eq_node(cdk::eq_node *const node, int lvl) = 0;
  virtual void do_ge_node(cdk::ge_node *const node, int lvl) = 0;
  virtual void do_gt_node(cdk::gt_node *const node, int lvl) = 0;
  virtual void do_integer_node(cdk::integer_node *const node, int lvl) = 0;
  virtual void do_le_node(cdk::le_node *const node, int lvl) = 0;
  virtual void do_lt_node(cdk::lt_node *const node, int lvl) = 0;
  virtual void do_mod_node(cdk::mod_node *const node, int lvl) = 0;
  virtual void do_mul_node(cdk::mul_node *const node, int lvl) = 0;
  virtual void do_neg_node(cdk::neg_node *const node, int lvl) = 0;
  virtual void do_ne_node(cdk::ne_node *const node, int lvl) = 0;
  virtual void do_nil_node(cdk::nil_node *const node, int lvl) = 0;
  virtual void do_not_node(cdk::not_node *const node, int lvl) = 0;
  virtual void do_or_node(cdk::or_node *const node, int lvl) = 0;
  virtual void do_rvalue_node(cdk::rvalue_node *const node, int lvl) = 0;
  virtual void do_sequence_node(cdk::sequence_node *const node, int lvl) = 0;
  virtual void do_string_node(cdk::string_node *const node, int lvl) = 0;
  virtual void do_sub_node(cdk::sub_node *const node, int lvl) = 0;
  virtual void do_variable_node(cdk::variable_node *const node, int lvl) = 0;

#else
  void do_add_node(cdk::add_node *const node, int lvl);
  void do_and_node(cdk::and_node *const node, int lvl);
  void do_assignment_node(cdk::assignment_node *const node, int lvl);
  void do_data_node(cdk::data_node *const node, int lvl);
  void do_div_node(cdk::div_node *const node, int lvl);
  void do_double_node(cdk::double_node *const node, int lvl);
  void do_eq_node(cdk::eq_node *const node, int lvl);
  void do_ge_node(cdk::ge_node *const node, int lvl);
  void do_gt_node(cdk::gt_node *const node, int lvl);
  void do_integer_node(cdk::integer_node *const node, int lvl);
  void do_le_node(cdk::le_node *const node, int lvl);
  void do_lt_node(cdk::lt_node *const node, int lvl);
  void do_mod_node(cdk::mod_node *const node, int lvl);
  void do_mul_node(cdk::mul_node *const node, int lvl);
  void do_neg_node(cdk::neg_node *const node, int lvl);
  void do_ne_node(cdk::ne_node *const node, int lvl);
  void do_nil_node(cdk::nil_node *const node, int lvl);
  void do_not_node(cdk::not_node *const node, int lvl);
  void do_or_node(cdk::or_node *const node, int lvl);
  void do_rvalue_node(cdk::rvalue_node *const node, int lvl);
  void do_sequence_node(cdk::sequence_node *const node, int lvl);
  void do_string_node(cdk::string_node *const node, int lvl);
  void do_sub_node(cdk::sub_node *const node, int lvl);
  void do_variable_node(cdk::variable_node *const node, int lvl);

#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */
#endif /* __IN_VISITOR_HEADER__ */

